# Generated by Django 6.0.3 on 2026-03-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_autostat_alter_contact_created_at_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autostat',
            name='label',
            field=models.TextField(default='Anand'),
            preserve_default=False,
        ),
    ]
